version: 2

sources:
  - name: just_example_data
    description: "sample description 2"
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL

    tables:
      - name: store_sales
        description: "some description"
        columns:
          - name: created_at